### PR TITLE
Migrates to GH action matrix for E2E runs, preferring actions-setup-docker

### LINKED ISSUE #145: macOS+rust e2e tests in CI are pinned to an over two year old version of Docker
macOS+rust e2e tests in CI are pinned to an over two year old version of Docker, handled in `./ci/e2e/macos/install_docker.sh`. The rest of the matrix uses latest Docker per #159.

The impact is that we are blind to any issues that present only on recent versions of Docker + OS/x, such as #147. To mitigate this, people should manually run `make e2e` on a macbook on occasion.

The underlying problem is not that tests break, it is that they take too long to complete. The rust performance problem is being tracked in #152 and this issue should be revisited on any significant progress. However, this isn't a sure thing. For example, special casing in #158 resulted in half the time spent in macOS+rust e2e (on a modern MacBook Pro). However, GH actions run of those same tests failed on timeout after an hour.

There means there could be some possibilities that only change CI. For example, the descending performance could be related to memory or other environment details that differ between CI and a macbook pro. In other words, even if work on the root problem is slow progressing, there could be some changes to make things "fast enough" (40m?) to use normal Docker again.

### LINKED ISSUE #153: Delete ci/e2e/*/run_tests.sh scripts
Debugging issues like #152 are made more difficult due to scripts used to execute the e2e tests. It is not clear why the HOME directory is overridden only in OS/X, fo example, and this effects the GETENVOY_HOME used in tests.

`make e2e` should be invoked regardless of it it is CI or not. Any directories overridden for caching reasons should happen in the github workflow, not a shell script. This makes what's being overridden easier to see and integrate with github cache actions.

Once #130 is merged, we should clean up more of the shell scripts and integrate config more directly, as this will lead to better understanding and cache integrations.

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This moves special-casing to rust+macOS cell in a normal build matrix.
Issue #152 still needs investigation on how to get around the slowness.

Fixes #153

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
re-kicking build as the rust+macOS-latest matrix died

Screen Shot 2021-04-02 at 11 36 09 AM

**Comment by codefromthecrypt** [comment]
rebased on #158

**Comment by codefromthecrypt** [comment]
This shows the special-casing where >2year old docker is only used for the rust+macOS cell in the matrix

Screen Shot 2021-04-03 at 8 45 21 AM
Screen Shot 2021-04-03 at 8 45 14 AM

**Comment by codefromthecrypt** [comment]
rebased back to master to decouple this from other various PRs

**Comment by codefromthecrypt** [comment]
FYI: this all passes, the only reason it isn't showing that is because via the matrix, the action names drifted. So, it is expecting feedback from the old names. This is expected

**Comment by mathetake** [comment]
realized that TinyGo also experiences the increase of e2e running time, but this is vs running on the latest macos docker instead of 2yo one. Thanks for the work, I'm going to merge this.

**Comment by mathetake** [comment]
Workflow name `Run end-to-end (e2e) tests (macos-latest, rust, -v ${RUNNER_TEMP}:/tmp/cargohome -e CARGO_HOME=/t...` looks confusing, so I'm going to try `-v ${RUNNER_TEMP}:/tmp/cargohome -e CARGO_HOME=/t...` both for TinyGo and Rust so that it clears job names

**Comment by mathetake** [comment]
changed the job name according to https://futurestud.io/tutorials/github-actions-customize-the-job-name

**Comment by mathetake** [comment]
:raised_hands: 
Screenshot from 2021-04-05 09-48-35

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
good idea on rename and thanks for sharing!

**Pull request merged**
