### PR TITLE
Formats CI yaml and switches to a recent install_docker script

### PR DESCRIPTION
**Pull request by codefromthecrypt**
The former script to install docker fails and also has dead links
describing why it was written. This replaces the script with one updated
this month, and with history and license info about where it came from.

Signed-off-by: Adrian Cole <adrian@tetrate.io>

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
lint is inconsistent until #132 I will rebase and redo after that lands

**Comment by codefromthecrypt** [comment]
ok rebased

**Comment by codefromthecrypt** [comment]
opened #137 as multiple times I've noticed tests panic in ways unnecessary

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
This change fails on macos, unless we make further changes to the source. While the install works, the tests eventually appear to hang. That's ultimately because timeouts aren't working. For example, I clicked cancel on a run here:

https://github.com/tetratelabs/getenvoy/runs/2206165270

A timeout occurred in getenvoy_extension_run_test.go. The interesting thing is that it happened but didn't stop the tests then and there. For example, I canceled after 18.5 minutes, but the timeout happened in 10m. Other code around "getenvoy command exited unexpectedly" didn't seem to trigger, or we probably should have seen it in the log. My analysis may be faulty, so feel free to do your own while the run log is available!

```
NOTE: Shutting down early because a Ctrl-C ("terminated") was received.

• Failure [615.843 seconds]
getenvoy extension run
/home/runner/work/getenvoy/getenvoy/test/e2e/getenvoy_extension_run_test.go:36
  should create and run default example setup
  /home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.12.1/extensions/table/table.go:92
Scaffolding a new extension:
    category=envoy.filters.http, language=rust [It]
Generating files in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/216205242/extension:
    /home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.12.1/extensions/table/table_entry.go:43
* .getenvoy/extension/extension.yaml

* .gitignore
    Unexpected error:
* go.mod
        <*errors.fundamental | 0xc00000c048>: {
* go.sum
            msg: "reached timeout 10m0s",
* main.go
            stack: [0x13bfd25, 0x162a205, 0x10d8627, 0x10d7af9, 0x13c14d7, 0x13557a3, 0x13553bc, 0x1354987, 0x1358bef, 0x1358292, 0x135e531, 0x135e047, 0x135d837, 0x135fe26, 0x1361bb8, 0x1361828, 0x161bb18, 0x111c1af, 0x10720a1],
* main_test.go
        }
        reached timeout 10m0s
```

**Pull request merged**
